language: node_js
node_js:
- '8'
script: yarn ci
deploy:
  provider: npm
  email: 545792860@qq.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: qOu39bpkvUXuFrAubgT186R7EX+bPyf6hhHjQxQhjcS8tWf7ixUIFmPm4fqO64nhQr8ru3N7E61VDgJFW4quoARA4bDhGZ0SdTaHHgImxlW3Tphz8/ONGwKl8LWTJ2Eh2/AJTJIG24pOIaTgpFZ6AO0zBmwvVGtirF7UXGjzOR4FzzqrDs5DvUhAmL2FwC0LsPTlURFtIToKa+3FeAdDXjJsL/b1DdAphMceoYOwA3N2zhgKcPmBiHSs36+ALa0iIlOz59+EUdCKYSUoYAex8rF90HzpyFw6jOe83lQE5jvk2dMjjH/8oVrBN2L4cJxnxOtlY0k85SlDM972e1zvO2QUtSHC8/U/Dn44rcUq5ohhepppcuPk7Y1WDZTtYTjy0HedHUYZl7OincTJf0K4IUCi3zD8oH7B19/lTVXS23ZEL+tiwf6fP2BkbXJSBsCosVWqAgrhcmXosdRAbaD2nmVK6JAWl+qYWAVJXv3YAeBwuqgfiE4d6jlaZ0wL/5XI8L8et+FsEtjwwx6RNXCA4ox6UacJn/IVi3elQVozz17OWsV4ENZMpXuDox7L/DvEzQ3eGXvoBLSPdxiDeB4kAWJlhlxd9/EWphXqsfluFMmcRxx5448kH4T2jd7aMEGcVNVqTI8vH96US8p/DLAvmUh2RC8exftjO6LFhV1NzVI=
